apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      type: service
  template:
    metadata:
      {{ if .Values.prometheus.scrape }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '{{ .Values.prometheus.port }}'
        prometheus.io/path: '{{ .Values.prometheus.url }}'
      {{ end }}
      labels:
        app: {{ .Release.Name }}
        type: service
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.useTerminationMessagePolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          {{ end }}
          resources:
            limits:
              memory: {{ .Values.limit.memory.limit }}Mi
              cpu: {{ .Values.limit.cpu.limit }}m
            requests:
              memory: {{ .Values.limit.memory.request }}Mi
              cpu: {{ .Values.limit.cpu.request }}m
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.service.probe.readiness.url }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.service.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.service.probe.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.service.probe.liveness.url }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.service.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.service.probe.liveness.periodSeconds }}
          {{ if .Values.configuration }}
          volumeMounts:
            - name: configuration
              mountPath: {{ .Values.configuration.mountPath }}
              subPath: {{ .Values.configuration.subPath }}
          {{ end }}
          envFrom:
            {{ if .Values.configuration }}
            - configMapRef:
                name: {{ .Release.Name }}-config
            {{ end }}
      imagePullSecrets: 
        - name: {{ .Values.imagePullSecret }}
      {{ if .Values.configuration }}
      volumes:
        - name: configuration
          configMap:
            name: {{ .Release.Name }}-config
      {{ end }}
