{{ if .Values.service.ports }}
{{ if .Values.service.ports.rest }}
kind: Service
apiVersion: v1
metadata:
  name: svc-{{ .Release.Name }}-external
  labels:
    app: {{ .Release.Name }}
    type: service
    bound: external
spec:
  selector:
    app: {{ .Release.Name }}
    type: service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.ports.rest }}
      targetPort: {{ .Values.service.port }}
  externalIPs:
    - {{ .Values.externalIP }}
{{ end }}
{{ end }}