{{ if .Values.service.port }}
kind: Service
apiVersion: v1
metadata:
  name: svc-{{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    type: service
    bound: internal
spec:
  selector:
    app: {{ .Release.Name }}
    type: service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{ end }}