{{ if .Values.service.grpcport }}
kind: Service
apiVersion: v1
metadata:
  name: svc-{{ .Chart.Name }}-grpc
  labels:
    app: {{ .Chart.Name }}
    type: service
    bound: internal
spec:
  selector:
    app: {{ .Chart.Name }}
    type: service
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.grpcport }}
      targetPort: {{ .Values.service.grpcport }}
{{ end }}