{{ if .Values.service.grpcport }}
{{ if .Values.service.ports.grpc }}
kind: Service
apiVersion: v1
metadata:
  name: svc-{{ .Chart.Name }}-grpc-external
  labels:
    app: {{ .Chart.Name }}
    type: service
    bound: external
spec:
  selector:
    app: {{ .Chart.Name }}
    type: service
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.ports.grpc }}
      targetPort: {{ .Values.service.grpcport }}
  externalIPs:
    - {{ .Values.externalIP }}
{{ end }}
{{ end }}